SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCALE = 1

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_HEALTH = 3
PLAYER_SHIELD = 0
SHIELD_DURATION = 2000  # milliseconds

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 1
PLAYER_SHOT_NO = 1
PLAYER_SHOT_PIERCE = 0

WEAPONS = ["Rotator", "Laser"]
UPGRADES = ["Multi Shot", "Shield", "Bigger Bullets", "Extra Life", "Piercing Bullets", "Rapid Fire"]



SHOT_RADIUS = 7
SHOT_SPEED = 400

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Weapons:

ROTATOR_SPEED = 300
ROTATOR_RADIUS = 10
ROTATOR_RADIUS = 30

